### ISSUE TITLE
Feature request: Add site support for amazon book/ebook searches

### ISSUE THREAD

**Issue by Oxika95** [JonDerThan/annas-goodreads#13] opened 2023-12-31 04:17 UTC
Nothing wrong with it feel free to remove this just thought the extension was great and would love to see this feature added as I manage most of my e-library via amazon. Thanks for such a great extension!

**Comment by arogl** [comment] 2023-12-31 06:04
Try this one [Amazon.com LibGen integration](https://greasyfork.org/en/scripts/406924-amazon-com-libgen-integration)

@JonDerThan This also includes examples of how to search with author #2

**Comment by Oxika95** [comment] 2023-12-31 06:15
Wow that is actually perfect! Thanks so much!

**Comment by JonDerThan** [comment] 2023-12-31 08:52
Duplicate of #9. 

The script you linked is great @arogl, I didn't know about it! I wouldn't want to show a whole list of possibilities for each book on a list but it would work great on the main book pages. I'm currently working on the settings page, but this would make a nice addition, I'll open up an issue for it.

**Closed by JonDerThan** 2023-12-31 08:52 UTC
Labels: duplicate, wontfix
